server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        # ─── User Service ───────────────────────────────────────────────
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<remaining>.*), /${remaining}

        # ─── Search Service ─────────────────────────────────────────────
        - id: search-service
          uri: http://search-service:8082
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search/(?<remaining>.*), /${remaining}

        # ─── Transaction (Order) Service ─────────────────────────────────
        - id: transaction-service
          uri: http://transaction-service:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/(?<remaining>.*), /${remaining}

        # ─── Admin Service ──────────────────────────────────────────────
        - id: admin-service
          uri: http://admin-service:8084
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin/(?<remaining>.*), /${remaining}
