apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: d2FsbWFydA==   # base64 for "walmart"
