spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions_db
    username: tx_user
    password: tx_pw
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8082
logging:
  level:
    org.springframework: INFO
