version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: tx_user
      POSTGRES_PASSWORD: tx_pw
    ports:
      - "5432:5432"

  transactions:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8082:8080"
