apiVersion: v1
kind: Service
metadata:
  name: postgres-transaction
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service
  selector:
    app: postgres-transaction
