apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-transaction
spec:
  serviceName: "postgres-transaction"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-transaction
  template:
    metadata:
      labels:
        app: postgres-transaction
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-transaction-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-transaction-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-transaction-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-transaction-persistent-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-transaction-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
