name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: seifelfayoumy
  DOCKER_PASSWORD: ACLproject123

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AdminService, UserService, TransactionService, SearchService, apigateway]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: |
        mvn clean install -B
        mvn test

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: [AdminService, UserService, TransactionService, SearchService, apigateway]

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:buildcache,mode=max

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Update k8s manifests
      run: |
        cd k8s
        # Update image tags in deployment files
        for service in AdminService UserService TransactionService SearchService apigateway; do
          if [ -f "${service,,}-deployment.yaml" ]; then
            sed -i "s|image: .*${service,,}:.*|image: ${{ env.DOCKER_USERNAME }}/${service}:${{ github.sha }}|g" "${service,,}-deployment.yaml"
          fi
        done

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        cd k8s
        kubectl apply -f .
        kubectl get pods 