name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]


env:
  DOCKER_USERNAME: seifelfayoumy
  DOCKER_PASSWORD: ACLproject123

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AdminService, UserService, TransactionService, SearchService, apigateway]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: |
        mvn clean package -DskipTests

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: [AdminService, UserService, TransactionService, SearchService, apigateway]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: ./${{ matrix.service }}
      run: mvn clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Convert service name to lowercase
      id: lowercase
      run: |
        echo "SERVICE_LOWERCASE=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:buildcache,mode=max

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Minikube
      uses: medyagh/setup-minikube@master

    - name: Start Minikube
      run: |
        minikube start --memory=4096 --cpus=2
        minikube status

    - name: Deploy Infrastructure
      run: |
        cd k8s
        # Deploy and wait for each infrastructure component
        for dir in mongo redis rabbitmq postgres-user postgres-transaction; do
          if [ -d "$dir" ]; then
            echo "Deploying infrastructure: $dir"
            kubectl apply -f "$dir"
            echo "Waiting for $dir pods..."
            sleep 10
            kubectl get pods | grep $dir
          fi
        done
        
        # Give infrastructure time to initialize
        echo "Waiting for infrastructure to initialize..."
        sleep 30
        kubectl get pods

    - name: Deploy Services
      run: |
        cd k8s
        # Deploy services one by one
        for dir in admin user transaction search apigateway; do
          if [ -d "$dir" ]; then
            echo "Deploying service: $dir"
            kubectl apply -f "$dir"
            echo "Waiting for $dir service to start..."
            sleep 10
            kubectl get pods | grep $dir
            
            # Check logs if pods aren't ready
            pods=$(kubectl get pods | grep $dir | awk '{print $1}')
            for pod in $pods; do
              echo "Checking status of $pod"
              kubectl describe pod $pod
              echo "Logs of $pod"
              kubectl logs $pod --tail=50 || true
            done
          fi
        done

    - name: Verify Deployment
      run: |
        echo "All Deployments:"
        kubectl get deployments
        echo "\nAll Services:"
        kubectl get services
        echo "\nAll Pods:"
        kubectl get pods
        
        # Check status of non-ready pods
        echo "\nChecking non-ready pods:"
        kubectl get pods | grep -v "Running" | grep -v "NAME" || true
        
        # Show events
        echo "\nKubernetes Events:"
        kubectl get events --sort-by='.metadata.creationTimestamp' | tail -n 20 