name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]


env:
  DOCKER_USERNAME: seifelfayoumy
  DOCKER_PASSWORD: ACLproject123

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AdminService, UserService, TransactionService, SearchService, apigateway]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: |
        mvn clean package -DskipTests

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: [AdminService, UserService, TransactionService, SearchService, apigateway]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: ./${{ matrix.service }}
      run: mvn clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Convert service name to lowercase
      id: lowercase
      run: |
        echo "SERVICE_LOWERCASE=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_LOWERCASE }}:buildcache,mode=max

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Update k8s manifests
      run: |
        cd k8s
        # Update image tags in deployment files for each service
        for service in admin user transaction search apigateway; do
          if [ -d "$service" ]; then
            if [ -f "$service/$service-deployment.yaml" ]; then
              sed -i "s|image: .*${service}:.*|image: ${{ env.DOCKER_USERNAME }}/${service}:${{ github.sha }}|g" "$service/$service-deployment.yaml"
            fi
          fi
        done

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        kubectl config get-contexts
        kubectl config current-context

    - name: Deploy to Kubernetes
      run: |
        cd k8s
        # Apply configurations from each subdirectory
        for dir in */; do
          if [ -d "$dir" ]; then
            echo "Applying configurations in $dir"
            kubectl apply -f "$dir" --validate=false
          fi
        done
        kubectl get pods
        kubectl get services 